---
- name: download etcd
  become: yes
  become_user: root
  get_url:
    url: '{{etcd_tgz_url}}'
    dest: /root/{{etcd_tgz}}
    timeout: '{{etcd_download_timeout_seconds}}'
    mode: 0644

- name: unachive etcd
  become: yes
  become_user: root
  unarchive:
    remote_src: yes
    src: /root/{{etcd_tgz}}
    dest: '{{etcd_install_dir}}'
    creates: '{{etcd_install_dir}}/{{etcd_name}}'

- name: link etcd and etcdctl
  become: yes
  become_user: root
  file:
    src: '{{etcd_install_dir}}/{{etcd_name}}/{{item}}'
    dest: '{{etcd_install_dir}}/{{item}}'
    state: link
  with_items:
    - etcd
    - etcdctl
